spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
